CREATE TABLE [dbo].[CLIENTES]
(
	[IdCliente] INT NOT NULL PRIMARY KEY, 
    [NomeCliente] VARCHAR(MAX) NOT NULL
	[Email] VARCHAR(MAX) NOT NULL
)

CREATE TABLE [dbo].[PRODUTOS]
(
	[IdProduto] INT NOT NULL PRIMARY KEY, 
    [Nome] VARCHAR(MAX) NOT NULL
)
